### PR TITLE
Require AstroPy>=4.0

### LINKED ISSUE #762: cannot import name 'TimeNumeric' from 'astropy.time.formats'
#### Problem description

I am trying to work with 2.0.dev. I get the following error when trying to 
import lightkurve. It appears that TimeNumeric can not
be imported from astropy.time.formats.

#### Example

(base) [kmighell@ARSLA17110292:~/top/github/lightkurve]$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightkurve as lk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kmighell/top/github/lightkurve/lightkurve/__init__.py", line 22, in <module>
    from .time import *
  File "/Users/kmighell/top/github/lightkurve/lightkurve/time.py", line 7, in <module>
    from astropy.time.formats import TimeNumeric, day_frac
ImportError: cannot import name 'TimeNumeric' from 'astropy.time.formats' (//anaconda3/lib/python3.7/site-packages/astropy/time/formats.py)
>>> 

See above.

#### Expected behavior

I was expecting lightkurve to be imported without any problems.

#### Environment

-  platform: OSX
-  lightkurve version: v2.0.dev
-  installation method: pip

### PR DESCRIPTION
**Pull request by barentsen**
The new TimeSeries-based `LightCurve` class requires AstroPy 4.0 or later.

This PR updates `requirements.txt` accordingly, and should also fix #762.

### CODE REVIEW

**Comment by barentsen** [comment]
The `--remote-data` unit test failure is related to the fact that MAST is currently updating TESS Sector 15 data (cf. https://twitter.com/MAST_News/status/1275170759082721282 ).

Merging!
